#!/bin/bash
MY_TAG=${IMAGE_NAME##*:}
BASH_VER="${MY_TAG%%--*}"
echo "Building bash-$BASH_VER ($IMAGE_NAME)"

sed -i -e "s/\$BASH_VER/$BASH_VER/" Dockerfile
docker build --build-arg BASH_VER="$BASH_VER" -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
